# `xrender`, `glx` or `egl`
backend = "egl";
use-damage = true;

# vsync settings
vsync = false;
xrender-sync-fence = false;

# fading
fading = true;
fade-delta = 5;

# ensure these are disabled
dbus = false;
daemon = false;
dithered-present = false;

# window detection and ewmh
detect-client-leader = true;
detect-client-opacity = true;
detect-rounded-corners = true;
detect-transient = true;
mark-wmwin-focused = true;
#no-ewmh-fullscreen = true;
#unredir-if-possible = true;
use-ewmh-active-win = true;
