# Shadows
shadow = true;
shadow-radius = 7;
shadow-opacity = .75
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-color = "#000000";

# Fading
fading = true;
#fade-in-step = 0.03;
#fade-out-step = 0.03;
fade-delta = 2;

# Transparency / Opacity
frame-opacity = 0.7;
inactive-dim-fixed = true

# Corners
corner-radius = 0;

# true: disable compositor in fullscreen
# false: do not disable compositor (fewer bugs)
unredir-if-possible = true;

# true: use fallback for fullscreen detection
# false: use ewmh for fullscreen detection
no-ewmh-fullscreen = true;

# `xrender` for compat xorg
# `glx` for hwaccel xorg
# `egl` for wayland
backend = "glx";

# requires `xrandr`
#crop-shadow-to-monitor = false;

# bugfix
#no-fading-openclose = true;
#no-fading-destroyed-argb = true;
